# Generated by Django 5.1.6 on 2025-04-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('Monitor', 'Monitor'), ('Laptop', 'Laptop'), ('Escritorio', 'Escritorio'), ('Servidor', 'Servidor')], max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
