# Generated by Django 5.1.6 on 2025-04-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_products_productos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Product',
        ),
    ]
