# Generated by Django 5.1.6 on 2025-05-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_products_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='quantity',
            new_name='cantidad',
        ),
        migrations.RemoveField(
            model_name='products',
            name='name',
        ),
        migrations.AddField(
            model_name='products',
            name='marca',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='nombre',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='serial',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, choices=[('Monitor', 'Monitor'), ('Laptop', 'Laptop'), ('Escritorio', 'Escritorio'), ('Servidor', 'Servidor')], max_length=10, null=True),
        ),
    ]
