# Generated by Django 5.1.6 on 2025-05-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_quantity_products_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='marca',
            field=models.CharField(blank=True, choices=[('HP', 'HP'), ('Dell', 'Dell'), ('Lenovo', 'Lenovo'), ('Asus', 'Asus'), ('Acer', 'Acer'), ('Apple', 'Apple')], max_length=10, null=True),
        ),
    ]
