# Generated by Django 5.2.1 on 2025-05-29 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_products_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='products',
            name='serial',
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, choices=[('Monitor', 'Monitor'), ('Laptop', 'Laptop'), ('Escritorio', 'Escritorio'), ('Servidor', 'Servidor')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='marca',
            field=models.CharField(blank=True, choices=[('HP', 'HP'), ('Dell', 'Dell'), ('Lenovo', 'Lenovo'), ('Asus', 'Asus'), ('Acer', 'Acer'), ('Apple', 'Apple')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.products')),
            ],
        ),
    ]
